name = "miwil"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[vars]
# Behold feed URLs â€” replace with your real feed IDs from behold.so
BEHOLD_FEED_URL_ART = "https://feeds.behold.so/Kbd2hGmpjcBOVKmUNauX"
BEHOLD_FEED_URL_BJJ = "https://feeds.behold.so/siNeY1KShYAWIkgYZ1o5"

